import Head from 'next/head';
import Login from './components/Login';
import PositionMainPage from './components/PositionMainPage';
import {useAuth} from '../context/AuthContext';


function Home() {

  const {currentUser} = useAuth()
  console.log(currentUser);

  return (
    <>
    <Head>
      <title>Position Finder</title>
      <meta name="description" content="Generated by create next app"/>
    </Head>
      {currentUser ? ( <PositionMainPage/> ) : <Login/>}
    </>
  )
}


export default Home;